### PR TITLE
Update qt_gldraw.h

### PR DESCRIPTION
**Pull request by tokumeiwokiboushimasu**
Fix a build error.

### CODE REVIEW

**Comment by Artanejp** [comment]
Sorry for FTBFS.
This commit  still be working-in-progress, unavailable to build.
Also, commit with [DONOTBUILD] TAG is unavailable to build basically, this is only by my problem (；´Д｀)

**Comment by Artanejp** [comment]
And, thanks for this request, will merge (or not) for re-designing APIs of GUI and Sound driver.
This re-designing is not completed...
Will complete (and available to build) at next commit (and will make new branch for this changing ASAP).

**Comment by Artanejp** [comment]
For temporally workaround, make new branch api-change-sound-and-gui-20240723, and revert commit 04c4f350d on master.

**Comment by tokumeiwokiboushimasu** [comment]
Now the master branch can be compiled, so I close this pull request.

**Pull request closed without merging**
